### PR TITLE
feat: render tenant memory details

### PR DESCRIPTION
**Pull request by kunga**
Addition to #1177

image

### Test Status: <span style="color: orange;">⚠️ FLAKY</span>
📊 [Full Report](https://ydb-platform.github.io/ydb-embedded-ui/1623/)

| Total | Passed | Failed | Flaky | Skipped |
|:-----:|:------:|:------:|:-----:|:-------:|
| 134 | 130 | 0 | 4 | 0 |

### Bundle Size: ✅
Current: 66.07 MB | Main: 66.06 MB
Diff: +0.00 MB (0.00%)

✅ Bundle size unchanged.

<details>
<summary>ℹ️ CI Information</summary>

- Test recordings for failed tests are available in the full report.
- Bundle size is measured for the entire 'dist' directory.
- 📊 indicates links to detailed reports.
- 🔺 indicates increase, 🔽 decrease, and ✅ no change in bundle size.
</details>

### CODE REVIEW

**Comment by astandrik** [comment]
I think there is no need to render colors in tenant panel detailed memory view

**Comment by astandrik** [comment]
Wouldn't it be better to show memory distribution in common memory bar with popup as it implemented in nodes table?

**Comment by kunga** [comment]
> Wouldn't it be better to show memory distribution in common memory bar with popup as it's implemented in nodes table?

I think instead, as it is already detailed view it's ok to show that info without pop-up

Also we have something similar on storage tab:

image

> I think there is no need to render colors in tenant panel detailed memory view

It's the same colors as on bars, so you may even use it as a legend to node's bars

Also it helps to distinguish components with total and limits

**Comment by kunga** [comment]
WIP here https://github.com/ydb-platform/ydb/pull/11612

Right now you may check them on https://nda.ya.ru/t/1kywDbbe79fvSB

**Review by astandrik — APPROVED** [review]

**Pull request merged**
