### PR TITLE
docs: correct a readme typo

### PR DESCRIPTION
**Pull request by terasum**
Fix a tiny typo

### CODE REVIEW

**Comment by tsufiev** [comment]
@terasum Thank you for the contribution :)! Could you please change the commit title to 'docs: correct a readme typo'? We use [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) and commitlint check verifies that the commit title and message do not break conventional commits spec.

**Comment by terasum** [comment]
@tsufiev Hi, sorry for late, and I've fix the title

**Comment by tsufiev** [comment]
> @tsufiev Hi, sorry for late, and I've fix the title

To fix the commitlint error you have to make to keep a single commit (with changed title) and then do a force push into your remote branch.

**Comment by Raubzeug** [comment]
@terasum hi! You should change commit name like "fix: typo in readme". Conventional commits assume commit name should have a commit type with colon (fix: ) and a subject (typo in readme). And after that you should force push to your branch. Thank you in advance!

**Pull request closed without merging**
